### ISSUE TITLE
有点类似rjs，不过如何实现同一个文件打到不同的包？

### ISSUE THREAD

**Issue by social4hyq** [fex-team/fis3-packager-deps-pack#1]

**Comment by 2betop** [comment]
fis 中不允许同一个文件被打包到多个文件里面。如果想实现页面级别的 all in one 打包，请该用 loader 差价中的 allInOne 属性。

**Comment by small-joker** [comment]
同一个文件不能打包到多个文件里面，这个是fis里面的限制， 还是这个插件的限制。
有什么办法把这个限制处理掉吗？
像loader的allinone这种实现
