### ISSUE TITLE
支持process.env.NODE_ENV打包不同的文件吗？

### ISSUE THREAD

**Issue by lys623** [fex-team/fis3-packager-deps-pack#12]
if (process.env.NODE_ENV === 'production') {
    module.exports = require('./Root.prod')
} else if(process.env.NODE_ENV === 'dev'){
    module.exports = require('./Root.dev')
}else{
    module.exports = require('./Root.webpack')
}

如上代码，配置  
 'pkg/third.js': [
        '/modules/index.jsx:deps',
        '!/modules/**'
      ],
会同时打包上面的三个js，支持分别打包吗？

**Comment by 2betop** [comment]
不支持，想这个自己特许处理下吧，把某些你不喜欢打包的排除掉。

fis 做编译期做字面量分析的，此时并没有支持 js, 所以都会分析到。

**Comment by lys623** [comment]
谢谢回复
