### ISSUE TITLE
如何合并

### ISSUE THREAD

**Issue by justyy** [fex-team/fis3-packager-deps-pack#3]
r.js合并的话。要声明path配置。把所有js静态资源的路径都写出来。。不知道这里要怎么识别我所打包的js文件所调用的第三方组件的路径呢？我尝试了用了一下。只是把我主文件打包而已。并没有把依赖的文件打包进来啊

**Comment by 2betop** [comment]
居然不看 readme

**Comment by justyy** [comment]
我看了。。也测试过了的=。=。。但是并没有打包成功。是不是要依赖hook-amd那个库？如图下所示，我的依赖如下，
![image](https://cloud.githubusercontent.com/assets/7438323/12004996/985a7430-abc1-11e5-8e8d-a60b58f63beb.png)
然后。我配置如下。
![image](https://cloud.githubusercontent.com/assets/7438323/12005001/bc48075e-abc1-11e5-8b14-678fac50ab65.png)

是我配置错了？

对了。。这样，我也配置过
![image](https://cloud.githubusercontent.com/assets/7438323/12005008/35387e3c-abc2-11e5-8179-5363cfae1ed0.png)

难道是我理解能力有问题=。=

**Comment by 2betop** [comment]
是的，要配置 `fis3-hook-amd` ，然后配置 paths ，否则没法知道模块是哪定义的。

**Comment by xjchenhao** [comment]
@2betop 你好,问下有没有配置项来做合并后的压缩?

**Comment by 2betop** [comment]
不支持合并后的压缩，目前只能合并前压缩，然后合并就是简单合并。
