### ISSUE TITLE
reg.test is not a function

### ISSUE THREAD

**Issue by codering** [fex-team/fis3-packager-deps-pack#7]
使用时报错了， reg.test is not a function

``` js
   packager: fis.plugin('deps-pack', {
        useTrack : true, // 是否输出路径信息,默认为 true
        'pkg/app.js': [
            '/static/main.js',
            '/static/main.js:deps',
            '!/modules/vendor/*.js'
        ]
    })

```

fis3 版本  3.3.30

**Comment by 2betop** [comment]
主要是 deps-pack 的版本有点低

**Comment by codering** [comment]
应该用哪个版本？

**Comment by 2betop** [comment]
我三小时前才加的功能，你得用 `fis3-packager-deps-pack@0.1.0`

**Comment by codering** [comment]
恩，重装了下。现在有个警告
[WARNI] `packTo` or `fis-pack.json` is useless while you are using `fis3-packager-deps-packs`

fis-pack.json 怎么用的

**Comment by 2betop** [comment]
嗯，这就对了， 你一定是用 packTo ，用了这个插件后，packTo 无效了，所以还是删了吧。

**Comment by 2betop** [comment]
`fis-pack.json` 是外部的一个配置 pack 的文件，fis 编译的时候会自动读取传入。然而这个插件也不会处理它。

**Comment by codering** [comment]
用了这个插件后， 所有media用到packTo都应该去掉？ 可是我只想在 production下才用到这个插件

**Comment by 2betop** [comment]
当前 media

**Comment by codering** [comment]
那就不对了， 这个警告一直存在，尽管当前media没有用到packTo

**Comment by 2betop** [comment]
global 下面也不能用，因为当前 media 会继承 global 的

**Comment by codering** [comment]
恩，懂了。
